### PR TITLE
Try to also match contacts using SwiftyContacts

### PR DESCRIPTION
**Pull request by CarlAmbroselli**
For me on an iPhone, no contact names where resolved. This PR introduces the functionality to also fetch contacts for the given phone number using the SwiftyContacts library, which worked perfectly for me.

It's preferring results from SwiftyContacts, but keeps falling back to the existing contact fetching if no results are found.

### CODE REVIEW

**Comment by CarlAmbroselli** [comment]
For some reason the avatar doe not get set when backfilling old messages.

**Comment by CarlAmbroselli** [comment]
@EricRabil what are your thoughts on this? Have this version running since a week now and matches well

**Comment by CarlAmbroselli** [comment]
@EricRabil another friendly ping if we can merge this? I want to get off my fork an back to the main repo :)

**Comment by EricRabil** [comment]
Thanks for your contribution!

**Pull request merged**
